apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  revisionHistoryLimit: 3 # Number of old ReplicaSets to retain to allow rollback
  selector:
    matchLabels: # Same as labels in pod template
      app: nginx
      env: prod
  template:
    metadata:
      labels: # Same as selector
        app: nginx
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80

# Test this by delete a pod and see if it is recreated