apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: sample-app
spec:
  clusterIP: None
  ports:
  - port: 80
    name: web
  selector:
    app: sample-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  serviceName: nginx
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce